name: Workflow_Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu"]
        include:
          - os: ubuntu
            environment-file: environment.yml
            miniforge-variant: Mambaforge
            miniforge-version: 4.12.0-2

    steps:
      - uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          condarc-file: ${{ matrix.condarc-file }}
          environment-file: ${{ matrix.environment-file }}
          miniforge-variant: ${{ matrix.miniforge-variant }}
          miniforge-version: ${{ matrix.miniforge-version }}
          use-mamba: true
          auto-activate-base: false
          activate-environment: rnaseq
          use-only-tar-bz2: true # For caching purposes

      - name: modify samples.tsv
        run: |
          curr=$(pwd)/workflow/
          sed -i "s/REPLACE_ABSOLUTE_PATH/${curr//\//\\/}/g" workflow/samples.tsv
          sed -i "s/REPLACE_ROOT_DIR/${curr//\//\\/}/g" Snakefile

      - name: test workflow
        run: |
          conda activate rnaseq
          snakemake -j 4
