name: Workflow_Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu"]
        include:
          - os: ubuntu
            environment-file: environment.yml
            miniforge-variant: Mambaforge
            miniforge-version: 4.12.0-2

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          condarc-file: ${{ matrix.condarc-file }}
          environment-file: ${{ matrix.environment-file }}
          miniforge-variant: ${{ matrix.miniforge-variant }}
          miniforge-version: ${{ matrix.miniforge-version }}
          use-mamba: true
          auto-activate-base: false
          activate-environment: rnaseq

      - name: modify samples.tsv
        run: |
          curr=$(pwd)/workflow
          sed -i "s/\/home\/mabuelanin\/dib-dev\/denovo-rnaseq\/workflow\/samples/${curr//\//\\/}/g" workflow/samples.tsv
          sed -i "s/\/home\/mabuelanin\/dib-dev\/denovo-rnaseq\/workflow/${curr//\//\\/}/g" Snakefile

      - name: test workflow
        run: snakemake -j 4
